name: Ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm run build

    - run: npm test

    - name: Stash dist
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist/

  publish-npm:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'


    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/


      - name: Unstash dist
        uses: actions/download-artifact@master
        with:
          name: dist
          path: "dist/"

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

# publish-gpr:
#   runs-on: ubuntu-latest

#   steps:
#     - uses: actions/checkout@v1
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 12
#         registry-url: https://npm.pkg.github.com/
#         scope: '@SteffenKn'
#
#     - run: npm publish
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
